[tool.black]
skip-string-normalization = true
exclude = '''
/(
    \.git
  | \.ipython
  | \.mypy_cache
  | \.tox
  | \.venv
  | _build
  | buck-out
  | build
  | dist
  | alembic
)/
'''

[tool.coverage.report]
exclude_lines = [
  "pragma: no cover",
  "def __repr__",
  "if typing.TYPE_CHECKING:",
  "if TYPE_CHECKING:",
]

[tool.isort]
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true
ensure_newline_before_comments = true
line_length = 88
skip = [".ipython", "alembic"]
remove_redundant_aliases = true

[tool.semantic_release]
version_variable = [
	'comment/__version__.py:__version__',
]
upload_to_pypi = false
major_on_zero = false

[tool.pytest.ini_options]
env_override_existing_values = true
env_files = ['.env', '.test.env']
